### ISSUE TITLE
Rules Dialog not showing up properly in Firefox

### ISSUE THREAD

**Issue by pepperkick** [TF2PickupNET/TF2Pickup#113]
When you log in as a new user the accept rules dialog do not show up properly in Firefox.  
This is how it looks in Chrome
![rulesch](https://user-images.githubusercontent.com/8415891/32419908-2f6d7ce2-c2a8-11e7-8fba-dfa36d146a77.JPG)
This is how it looks in Firefox
![rules](https://user-images.githubusercontent.com/8415891/32419913-452ae86c-c2a8-11e7-865e-1186490be134.JPG)

**Comment by HenriBeck** [comment]
Should be fixed now

**Comment by HenriBeck** [comment]
![screenshot-2017-11-13 tf2pickup net web-based pickup system](https://user-images.githubusercontent.com/8514706/32743100-c46c1c0a-c8ab-11e7-927c-78c881c304bd.png)
That's how it looks for me

**Comment by HenriBeck** [comment]
Seemed to be an issue with the node version
