### ISSUE TITLE
Subs system

### ISSUE THREAD

**Issue by HenriBeck** [TF2PickupNET/TF2Pickup#214]
The sub system would need the following:
- Button for subbing a player on the match page
- A system for selecting subs / displaying them in the pickup queue
- TF2 server integration via log listener for subbing from in game
- Add a notification when a sub is requested and you are signed up for that class
- Display subs on the match page

**Comment by Kuferl** [comment]
- Allow several people to 'sign up' as sub and pick the person that fits in the best with elo
- Allow people to sub them out themself, this needs to have some sort of punishment though
